### ISSUE TITLE
`confirm_overwrite` parameter is sent downstream but never obeyed

### ISSUE THREAD

**Issue by marcusabate** [ToniRV/spark_vio_evaluation#16]
In several places we pass `confirm_overwrite` as a parameter, which if True asks the user to confirm before overwriting results files.

However, this parameter is not set anywhere in the experiments file or in any configs. Also, in some places where it should be passed along, it is actually not passed along at all.

Either we make this a config parameter and properly use it (recommend it be a class member instead of passed on a per-dataset basis), OR we get rid of it entirely because we always set it to False anyway.

@ToniRV thoughts?

**Comment by ToniRV** [comment]
Let's remove it to make things lean

**Comment by marcusabate** [comment]
Removed in #14 with e4906e16f4c3c8fe2b616d5195c6d98970fb6f89
