### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by violetteavi** [ToniRV/spark_vio_evaluation#37]
**Description:**
I tried to run the jupyter notebook frontend and got an error.

**Command:**
```
jupyter notebook
```

**Console output:**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e0819567fe5e> in <module>()
      8     plt.show()
      9 else:
---> 10     evt.draw_feature_tracking_stats(df_stats, True)

AttributeError: 'module' object has no attribute 'draw_feature_tracking_stats'
```

**Additional files:**
The zipped output logs:
[EuRoC.zip](https://github.com/ToniRV/Kimera-VIO-Evaluation/files/4806257/EuRoC.zip)

Please give also the following information:
* evo version number shown by `git rev-parse HEAD`
* Python version used:
* operating system and version (e.g. Ubuntu 16.04 or Windows 10):
* did you change the source code? (yes / no):
```

# remove this line and paste your config HERE

```

**Comment by marcusabate** [comment]
@violetteavi should be fixed in #45
