### ISSUE TITLE
Plotting notebooks need a library

### ISSUE THREAD

**Issue by marcusabate** [ToniRV/spark_vio_evaluation#7]
The plotting notebooks have code duplication because many helper functions are copied over. For these shared functions it would be useful to have a small python library available to the notebooks in the same folder, containing those functions. This would make them much cleaner.

The downside is this would be a bit less transparent to users who want to quickly open up notebooks and run tests, not knowing they might need to alter some functions.

**Comment by marcusabate** [comment]
@marcusabate 

- [x] Common to DatasetEvaluator functions
- [ ] Need unit tests for all these functions!

**Comment by jingnanshi** [comment]
@marcusabate Is it possible to have command line options that specify the input folder and/or the gt trajectory file? As far as I can tell those are the only inputs required.

**Comment by marcusabate** [comment]
Solved in #45

**Comment by marcusabate** [comment]
@jingnanshi just saw this, those inputs are spec'd in the experiments file but we can definitely add commandline if you think that would be better. Open a new issue and tag me in it.
